package com.tcsx.studentinfo.studentinformationsystem.model;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;

@DynamoDBTable(tableName = "Professor")
public class Professor {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	String id;
	@DynamoDBAttribute
	String firstName;
	@DynamoDBAttribute
	String lastName;
	@DynamoDBAttribute
	@DynamoDBTypeConvertedJson
	Set<String> courses;

	
	public Professor() {
		courses = new HashSet<>();
	}
	
	public Professor(String id, String firstName, String lastName, Set<String> courses) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.courses = courses;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Set<String> getCourses() {
		return courses;
	}

	public void setCourses(Set<String> courses) {
		this.courses = courses;
	}

	public boolean addCourse(Course course) {
		return courses.add(course.getId());
	}
	
	public boolean deleteCourseById(String courseId) {
		return courses.remove(courseId);
	}
	
}
