package com.tcsx.studentinfo.studentinformationsystem.model;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import java.util.Map.Entry;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import com.fasterxml.jackson.annotation.JsonIgnore;

@DynamoDBTable(tableName = "Student")
public class Student {
	@DynamoDBHashKey
	private String studentId;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private String image;
	@DynamoDBAttribute
	@DynamoDBTypeConvertedJson
	private Set<String> courses;
	@DynamoDBAttribute
	private String program;
	@DynamoDBAttribute
	private String email;
	
	public Student() {
		courses = new HashSet<>();
	}
	
	public Student(String studentId, String name, String image, Set<String> courses, String program, String email) {
		
		super();
		this.studentId = studentId;
		this.name = name;
		this.image = image;
		this.courses = courses;
		this.program = program;
		this.email = email;
	}
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean deleteCourseById(String id) {
		return courses.remove(id);
	}
	
	public void addCourse(String course) {
		courses.add(course);
	}

	public Set<String> getCourses() {
		return courses;
	}

	public void setCourses(Set<String> courses) {
		this.courses = courses;
	}

	public String getProgram() {
		return program;
	}

	public void setProgram(String program) {
		this.program = program;
	}

	public String getStudentId() {
		return studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	
	
}
